### ISSUE TITLE
[LPR2] lprws-test.sds.dsdn.dk  - kald til PlainContactService save fejler fra intbatch1.test.cosmic.rsyd.net

### ISSUE THREAD

**Issue by MogensHessellund** [scandihealth/lpr3-docs#173]
Invoking save fails with the following error.

2018-08-22 13:01:05,082 WARN  [dk.logica.cosmic.LPR.export.LPRExporter] (http-10.221.165.54-9180-2) Export af LPRContact fejlede for CPR : 2712310FU1 kontakt start/slut : 28-03-2018 11:57 / 23-05-2018 14:46
javax.xml.ws.soap.SOAPFaultException: An internal error occurred in the LPR system: java.lang.RuntimeException: Couldn't save contact object 
                             at org.jboss.ws.core.jaxws.SOAPFaultHelperJAXWS.getSOAPFaultException(SOAPFaultHelperJAXWS.java:84)
                             at org.jboss.ws.core.jaxws.binding.SOAP11BindingJAXWS.throwFaultException(SOAP11BindingJAXWS.java:107)
                             at org.jboss.ws.core.CommonSOAPBinding.unbindResponseMessage(CommonSOAPBinding.java:579)
                             at org.jboss.ws.core.CommonClient.invoke(CommonClient.java:381)
                             at org.jboss.ws.core.jaxws.client.ClientImpl.invoke(ClientImpl.java:290)
                             at org.jboss.ws.core.jaxws.client.ClientProxy.invoke(ClientProxy.java:170)
                             at org.jboss.ws.core.jaxws.client.ClientProxy.invoke(ClientProxy.java:150)
                             at com.sun.proxy.$Proxy2662.save(Unknown Source)
                             at dk.logica.cosmic.lpr.common.LPRServicesWebserviceDelegator.save(LPRServicesWebserviceDelegator.java:98)
                             at dk.logica.cosmic.lpr.common.LPRServicesWebserviceDelegator.saveLPRData(LPRServicesWebserviceDelegator.java:73)

Networkdump shows lprws-test.sds.dsdn.dk sends RST = Reset command.
See Wireshark screenshot

My assumption is that lprws-test.sds.dsdn.dk reject our save request.

**Comment by MogensHessellund** [comment]
![wireshark](https://user-images.githubusercontent.com/1227869/44523301-acae0580-a6d9-11e8-82e8-b43e0a5602c5.png)

**Comment by TueCN** [comment]
Hi Mogens,

First off, this is an english forum, but luckily I'm Danish so I understand your post :)

Can you give a specific timestamp for when this happened? I could not see any recent problems related to this in our log files. 
Can you paste the HTTP request here so we can try and reproduce the problem?

**Comment by MogensHessellund** [comment]
Første linje i logfilen overfor indeholder da et tidspunkt ?!? 
2018-08-22 13:01:05,082

Da det er TLS så er det vel encrypted. Men jeg godt sende dig wireshark pcap-fil hvis det har interesse.

Simon Mikkelsen kender til problematikken.

**Comment by TueCN** [comment]
The posted log entry is from your internal system, but thank you for pointing out that the timestamp is in fact the time that the web service was called.

I found several errors in our logs at 13:01 relating to the LPR2 web service [PlainContactService](https://lprws-test.sds.dsdn.dk/ws/PlainContactService?WSDL) and assume your error is one of them. 

Errors on the LPR2 web service on lprws-test.sds.dsdn.dk have already been found internally and we are investigating what the problem is.

**Comment by TueCN** [comment]
**RESOLUTION**
A unintended change had been made to the LPR2 web service, PlainContactService in LPR v3.0.x. 
This change has been reverted and the functionality similar to LPR v2.6.x restored.

**Comment by simon-dxc** [comment]
@MogensHessellund - If everything is fine could you please close the issue.
We will close it thuesday next week if we haven't heard from you.
